apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio
type: Opaque
data:
  # Base64 encoded values - update these with your actual values
  # You can generate base64 values using: echo -n "your_value" | base64
  MINIO_ROOT_USER: bWluaW8=  # "minio" in base64 - CHANGE THIS
  MINIO_ROOT_PASSWORD: TWluaW9AUTEyMw==  # "Minio@123" in base64 - CHANGE THIS
  MINIO_DOMAIN: bWluaW8ueW91ci1kb21haW4uY29t  # "minio.your-domain.com" in base64 - CHANGE THIS